// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptPDF(arg1, arg2) {
  return window['go']['main']['App']['DecryptPDF'](arg1, arg2);
}

export function EncryptPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['EncryptPDF'](arg1, arg2, arg3);
}

export function GetPDFPermissions(arg1, arg2) {
  return window['go']['main']['App']['GetPDFPermissions'](arg1, arg2);
}

export function PickPDF() {
  return window['go']['main']['App']['PickPDF']();
}
