// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptPDF(arg1:string,arg2:string):Promise<string>;

export function EncryptPDF(arg1:string,arg2:string,arg3:number):Promise<string>;

export function GetPDFPermissions(arg1:string,arg2:string):Promise<number>;

export function PickPDF():Promise<string>;
